name: Deploy to Droplet
env:
  IMAGE_NAME: kazimovzaman2/agileflow-landing:latest
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git Clone Repository
        uses: actions/checkout@v2
      - name: Login To Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build --file Dockerfile -t ${{ env.IMAGE_NAME }} .
      - name: Push Docker Image
        run: docker push ${{ env.IMAGE_NAME }}
